steps:
  - id: build-push
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -ex

        docker build -t -t=us-central1-docker.pkg.dev/com-seankhliao/build/blogengine:latest .
        docker push -t=us-central1-docker.pkg.dev/com-seankhliao/build/blogengine:latest

  - id: sign-latest
    name: 'gcr.io/projectsigstore/cosign'
    env:
      - 'TUF_ROOT=/tmp' # cosign tries to create $HOME/.sigstore
      - 'COSIGN_EXPERIMENTAL=1'
      - 'GOOGLE_SERVICE_ACCOUNT_NAME=cosign-signer@com-seankhliao.iam.gserviceaccount.com'
    args:
      - 'sign'
      - 'us-central1-docker.pkg.dev/com-seankhliao/build/blogengine:latest'
